# [S]소스로부터 키클락 이미지 만들기
FROM registry.access.redhat.com/ubi9 AS ubi-micro-build

ENV KEYCLOAK_VERSION 25.0.2
ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

RUN dnf install -y tar gzip

ADD $KEYCLOAK_DIST /tmp/keycloak/

# The next step makes it uniform for local development and upstream built.
# If it is a local tar archive then it is unpacked, if from remote is just downloaded.
RUN (cd /tmp/keycloak && \
    tar -xvf /tmp/keycloak/keycloak-*.tar.gz && \
    rm /tmp/keycloak/keycloak-*.tar.gz) || true

RUN mv /tmp/keycloak/keycloak-* /opt/keycloak && mkdir -p /opt/keycloak/data
RUN chmod -R g+rwX /opt/keycloak

ADD ubi-null.sh /tmp/
RUN bash /tmp/ubi-null.sh java-17-openjdk-headless glibc-langpack-en findutils

FROM registry.access.redhat.com/ubi9-micro
ENV LANG en_US.UTF-8

COPY --from=ubi-micro-build /tmp/null/rootfs/ /
COPY --from=ubi-micro-build --chown=1000:0 /opt/keycloak /opt/keycloak

RUN echo "keycloak:x:0:root" >> /etc/group && \
    echo "keycloak:x:1000:0:keycloak user:/opt/keycloak:/sbin/nologin" >> /etc/passwd

USER 1000

EXPOSE 8080
EXPOSE 8443

#ENTRYPOINT [ "/opt/keycloak/bin/kc.sh" ]
# [E]소스로부터 키클락 이미지 만들기
# Keycloak 베이스 이미지 설정
#FROM quay.io/keycloak/keycloak:23.0.5 as builder

# 건강 상태 및 메트릭스 지원 활성화, 데이터베이스 벤더 구성
ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_DB=mysql

WORKDIR /opt/keycloak

# 디몬스트레이션 목적으로만 사용되는 인증서 생성
# 프로덕션 환경에서는 적절한 인증서 사용 필요
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore


# Keycloak 커스텀 프로바이더 설치
COPY apple-identity-provider-1.13.0.jar /opt/keycloak/providers/
COPY knowk-keycloak-userapp-theme.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

# Keycloak 이미지 최종 레이어
#FROM quay.io/keycloak/keycloak:25.0.2
#COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Database, Keycloak 서버 구성 및 관리자 계정 설정
ENV KC_DB=mysql \
    KC_DB_URL=jdbc:mysql://sandbox01-shared-mysql.cluster-c1ekmeygyqx9.ap-northeast-2.rds.amazonaws.com:3306/keycloak \
    KC_DB_USERNAME=developer \
    KC_DB_PASSWORD=4(wn|>eLC^d7g@9o \
    KC_HOSTNAME=keycloak.sand01.knowk.io \
    KEYCLOAK_ADMIN=admin \
    KEYCLOAK_ADMIN_PASSWORD=admin \
    PROXY_ADDRESS_FORWARDING=true \
    KC_FEATURES=admin-fine-grained-authz,token-exchange,persistent-user-sessions \
    KC_PROXY=edge

# Keycloak 실행 명령
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--features=admin-fine-grained-authz,token-exchange,persistent-user-sessions"]
