# Keycloak 베이스 이미지 설정
FROM quay.io/keycloak/keycloak:23.0.5 as builder

# 건강 상태 및 메트릭스 지원 활성화, 데이터베이스 벤더 구성
ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_DB=mariadb

WORKDIR /opt/keycloak

# 디몬스트레이션 목적으로만 사용되는 인증서 생성
# 프로덕션 환경에서는 적절한 인증서 사용 필요
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore


# Keycloak 커스텀 프로바이더 설치
COPY apple-identity-provider-1.10.0.jar /opt/keycloak/providers/
COPY knowk-keycloak-userapp-theme.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build

# Keycloak 이미지 최종 레이어
FROM quay.io/keycloak/keycloak:23.0.5
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Database, Keycloak 서버 구성 및 관리자 계정 설정
ENV KC_DB=mariadb \
    KC_DB_URL=jdbc:mariadb://sandbox01-shared-mysql.cluster-c1ekmeygyqx9.ap-northeast-2.rds.amazonaws.com:3306/keycloak \
    KC_DB_USERNAME=developer \
    KC_DB_PASSWORD=4(wn|>eLC^d7g@9o \
    KC_HOSTNAME=keycloak.sand01.knowk.io \
    KEYCLOAK_ADMIN=admin \
    KEYCLOAK_ADMIN_PASSWORD=admin \
    PROXY_ADDRESS_FORWARDING=true \
    KC_FEATURES=admin-fine-grained-authz,token-exchange \
    KC_PROXY=edge

# Keycloak 실행 명령
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--features=admin-fine-grained-authz,token-exchange"]

